### ISSUE TITLE
data availability

### ISSUE THREAD

**Issue by eminorhan** [Neuroprosthetics-Lab/nejm-brain-to-text#1]
Thank you for your commitment to making the data public. The Dryad link on the README page currently points to the Google home page. I was just wondering if you have a time frame for when the data will be released.

**Comment by nckcard** [comment]
Hi, sorry for the delay, I've been busier than expected since the paper has released. I will try to get this done within the next week or two (i.e., by mid-September)

**Comment by nckcard** [comment]
To update you on this: I have uploaded the first version of available data to Dryad, but it has been stuck "processing" for about a week. Hopefully it will be available soon.

**Comment by eminorhan** [comment]
Thank you very much for letting me know. Looking forward to it.

**Comment by eminorhan** [comment]
@nckcard I'm really sorry to be a nag, but I was just wondering if there's any update on the availability of the data. Thank you!

**Comment by jaivardhankapoor** [comment]
> We are also aiming to share actual T15 neural data in early 2025.

Hi, I'd love to use the raw data for my research, is there an updated timeline on the release of this data? Happy to continue the correspondence on email!

Thanks a lot,
Jaivardhan Kapoor
University of Tuebingen

**Comment by nckcard** [comment]
Hi, our schedule was pushed back slightly but we should be on track to release data soon this summer. Stay tuned.

**Comment by jaivardhankapoor** [comment]
> Hi all, data release should be imminent (within the next week, hopefully). We are just waiting for Dryad to approve the new data upload. You can check out the `b2txt25` branch of this repository (which will be merged into `main` soon) for new code and documentation regarding phoneme decoder model training, language models, and model evaluation.

Great news, thank you so much for following up on this!
